time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "medium_range_blend"
InputForcings: [3] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NBM_test/GFS"]
InputForcingTypes: ["GRIB2"]
InputMandatory: [1]
OutputFrequency: 60
OutDir: "./Unit_Test_Output/Medium_range_blend"
ScratchDir: "./Unit_Test_Output/Medium_range_blend"
compressOutput: 0
floatOutput: 0
RetroFlag: 0
AnAFlag: 0
BDateProc: -9999
EDateProc: -9999
LookBack : -9999
RefcstBDateProc: "202302211200"
RefcstEDateProc: "202302211300"
ForecastFrequency: 360
ForecastShift: 0
ForecastInputHorizons: [14400]
ForecastInputOffsets: [0]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/geo_em_CONUS.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/GEOGRID_LDASOUT_Spatial_Metadata_CONUS.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [3]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [3]
SwBiasCorrection: [0]
LwBiasCorrection: [3]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [2]
ShortwaveDownscaling: [1]
PressureDownscaling: [1]
PrecipDownscaling: [1]
HumidityDownscaling: [1]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Medium_Range"]
SuppPcp: [8]
SuppPcpForcingTypes: ['GRIB2']
SuppPcpDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NBM_test/NBM']
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Medium_Range'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFraq: 0
