time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "long_range"
InputForcings: [7] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/CFS_test"]
InputForcingTypes: ["GRIB2"]
InputMandatory: [1]
OutputFrequency: 60
OutDir: "./Unit_Test_Output/Long_range"
ScratchDir: "./Unit_Test_Output/Long_range"
compressOutput: 0
floatOutput: 0
RetroFlag: 0
AnAFlag: 0
BDateProc: -9999
EDateProc: -9999
LookBack : -9999
RefcstBDateProc: "202302140000"
RefcstEDateProc: "202302150000"
ForecastFrequency: 360
ForecastShift: 0
ForecastInputHorizons: [43200]
ForecastInputOffsets: [0]
GeogridIn: "./NextGen_Domains/unstructured/SCHISM_grid_forcing_engine.nc"
SpatialMetaIn: ""
GRID_TYPE: "unstructured"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemConn: 'elementConn'
NumElemConn: 'numElementConn'
HGTVAR: 'Node_Elevations'
HGTVAR_ELEM: 'Element_Elevations'
IgnoredBorderWidths: [0]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [0]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [0]
SwBiasCorrection: [0]
LwBiasCorrection: [0]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [0]
ShortwaveDownscaling: [0]
PressureDownscaling: [0]
PrecipDownscaling: [0]
HumidityDownscaling: [0]
DownscalingParamDirs: ["./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: 1
custom_input_fcst_freq: []
includeLQFraq: 0
