time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "medium_range_ndfd"
InputForcings: [3, 25]
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NDFD_test/GFS",'/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NDFD_test/NDFD']
InputForcingTypes: ["GRIB2","GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/Medium_range"
Output: 1
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202405280000"
ForecastFrequency: 360
ForecastShift: 0
ForecastInputHorizons: [14400,14400]
ForecastInputOffsets: [0,0]
GeogridIn: "./NextGen_Domains/hydrofabric/NextGen_Hyfab_VPU_06_ESMF_Mesh.nc"
SpatialMetaIn: ""
GRID_TYPE: "hydrofabric"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemID: 'element_id'
ElemConn: 'elementConn'
NumElemConn: 'numElementConn'
HGTVAR: 'Element_Elevation'
SLOPE: 'Element_Slope'
SLOPE_AZIMUTH: 'Element_Slope_Azmuith'
IgnoredBorderWidths: [0,0]
RegridOpt: [1,2]
ForcingTemporalInterpolation: [0,0]
TemperatureBiasCorrection: [0,0]
PressureBiasCorrection: [0,0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,0]
ShortwaveDownscaling: [0,0]
PressureDownscaling: [0,0]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,0]
DownscalingParamDirs: ["./NWM_Params","./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFrac: 1
