time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "AORC_Blend"
InputForcings: [12,23]
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/AORC_Idalia","/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/ERA5_CONUS"]
InputForcingTypes: ["NETCDF4","NETCDF"]
InputMandatory: [1,1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/AORC"
Output: 1
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : 8700
RefcstBDateProc: "202309030000"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [14400,14400]
ForecastInputOffsets: [0,0]
GeogridIn: "./NextGen_Domains/unstructured/SCHISM_Atlantic_ESMF_Mesh.nc"
SpatialMetaIn: ""
GRID_TYPE: "unstructured"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemConn: 'elementConn'
NumElemConn: 'numElementConn'
HGTVAR: 'Node_Elevations'
HGTVAR_ELEM: 'Element_Elevations'
IgnoredBorderWidths: [0,0]
RegridOpt: [1,1]
ForcingTemporalInterpolation: [0,0]
TemperatureBiasCorrection: [0,0]
PressureBiasCorrection: [0,0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,0]
ShortwaveDownscaling: [0,0]
PressureDownscaling: [0,0]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,0]
DownscalingParamDirs: ["./NWM_Params","./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFraq: 0
