time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "Extended_AnA"
InputForcings: [6,5] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/RAP", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/HRRR"]
InputForcingTypes: ["GRIB2", "GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
OutDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
ScratchDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
compressOutput: 0
floatOutput: 0
RetroFlag: 0
AnAFlag: 1
BDateProc: -9999
EDateProc: -9999
LookBack : 1680
RefcstBDateProc: "202308221600"
RefcstEDateProc: "202308221700"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [60, 60]
ForecastInputOffsets: [0, 0]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/geo_em_CONUS.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain/GEOGRID_LDASOUT_Spatial_Metadata_CONUS.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0, 10]
RegridOpt: [1, 1]
ForcingTemporalInterpolation: [0, 0]
TemperatureBiasCorrection: [0, 4]
PressureBiasCorrection: [0, 0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,4]
SwBiasCorrection: [0,2]
LwBiasCorrection: [0,2]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [2,2]
ShortwaveDownscaling: [1,1]
PressureDownscaling: [1,1]
PrecipDownscaling: [0,0]
HumidityDownscaling: [1,1]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/AnA"]
SuppPcp: [11]
SuppPcpForcingTypes: ['GRIB2']
SuppPcpDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/MRMS_CONUS', '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/StageIV_CONUS']
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/AnA'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFraq: 0
