time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "AnA"
InputForcings: [20] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/Alaska_ExtAnA/HRRR_Alaska"]
InputForcingTypes: ["GRIB2"]
InputMandatory: [1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/extended_AnA"
compressOutput: 0
floatOutput: 0
AnAFlag: 1
LookBack : 180
RefcstBDateProc: "202309271700"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [60]
ForecastInputOffsets: [0]
GeogridIn: "./NextGen_Domains/hydrofabric/Alaska_ESMF_Mesh.nc"
SpatialMetaIn: ""
GRID_TYPE: "hydrofabric"
NodeCoords: 'nodeCoords'
ElemCoords: 'centerCoords'
ElemConn: 'elementConn'
ElemID: 'element_id'
NumElemConn: 'numElementConn'
HGTVAR: 'Element_Elevation'
SLOPE: 'Element_Slope'
SLOPE_AZIMUTH: 'Element_Slope_Azmuith'
IgnoredBorderWidths: [10]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [0]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [0]
SwBiasCorrection: [0]
LwBiasCorrection: [0]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [0]
ShortwaveDownscaling: [0]
PressureDownscaling: [0]
PrecipDownscaling: [0]
HumidityDownscaling: [0]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Alaska"]
SuppPcp: [11]
SuppPcpForcingTypes: ['GRIB2']
SuppPcpDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/Alaska_ExtAnA/MRMS_Alaska', '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/Alaska_ExtAnA/STAGEIV_Alaska']
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Alaska'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFraq: 0
