time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "NWM"
InputForcings: [27]
InputForcingDirectories: ["/home/NWMv3_Hawaii"]
InputForcingTypes: ["NWM"]
InputMandatory: [1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/NWM"
Output: 0
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999.
RefcstBDateProc: "200301011300"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [14400]
ForecastInputOffsets: [0]
NWM_Geogrid: "./NWMv3.0_config/parm/domain/geo_em_HI.nc"
GeogridIn: "./NWMv3.0_config/parm/domain/geo_em_HI.nc"
SpatialMetaIn: "./NWMv3.0_config/parm/domain/GEOGRID_LDASOUT_Spatial_Metadata_HI.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [0]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [0]
SwBiasCorrection: [0]
LwBiasCorrection: [0]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [0]
ShortwaveDownscaling: [0]
PressureDownscaling: [0]
PrecipDownscaling: [0]
HumidityDownscaling: [0]
DownscalingParamDirs: ["./NWM_Params"]
SuppPcp: []
SuppPcpForcingTypes: ''
SuppPcpDirectories: ''
SuppPcpParamDir: ''
RegridOptSuppPcp: []
SuppPcpTemporalInterpolation: []
SuppPcpInputOffsets: []
SuppPcpMandatory: []
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFrac: 0
