time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "Extended_AnA"
InputForcings: [13] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NAM_Nest_Hawaii"]
InputForcingTypes: ["GRIB2"]
InputMandatory: [1]
OutputFrequency: 60
OutDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
ScratchDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
compressOutput: 0
floatOutput: 0
RetroFlag: 0
AnAFlag: 1
BDateProc: -9999
EDateProc: -9999
LookBack : 180
RefcstBDateProc: "202309250000"
RefcstEDateProc: "202309250600"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [60]
ForecastInputOffsets: [0]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain_hawaii/geo_em_HI.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain_hawaii/GEOGRID_LDASOUT_Spatial_Metadata_HI.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0]
RegridOpt: [1]
ForcingTemporalInterpolation: [0]
TemperatureBiasCorrection: [0]
PressureBiasCorrection: [0]
HumidityBiasCorrection: [0]
WindBiasCorrection: [0]
SwBiasCorrection: [0]
LwBiasCorrection: [0]
PrecipBiasCorrection: [0]
TemperatureDownscaling: [1]
ShortwaveDownscaling: [1]
PressureDownscaling: [1]
PrecipDownscaling: [0]
HumidityDownscaling: [1]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Hawaii"]
SuppPcp: [6]
SuppPcpForcingTypes: ['GRIB2']
SuppPcpDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/MRMS_Hawaii']
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/Hawaii'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: '1'
custom_input_fcst_freq: []
includeLQFraq: 0
