time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "short_range"
InputForcings: [6,5] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/RAP", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/HRRR"]
InputForcingTypes: ["GRIB2", "GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
OutDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
ScratchDir: "/scratch2/NCEPDEV/ohd/Jason.Ducker/ngen-master/extern/test_bmi_NextGen_Forcings_Engine/Unit_Test_Output/extended_AnA"
compressOutput: 0
floatOutput: 0
RetroFlag: 0
AnAFlag: 1
BDateProc: -9999
EDateProc: -9999
LookBack : 1740
RefcstBDateProc: "202308221500"
RefcstEDateProc: "202308221600"
ForecastFrequency: 60
ForecastShift: 0
ForecastInputHorizons: [60, 60]
ForecastInputOffsets: [0, 0]
GeogridIn: "./NextGen_Domains/gridded/netcdf_gridded_dummy.nc"
SpatialMetaIn: ""
GRID_TYPE: "gridded"
LONVAR: 'Longitude'
LATVAR: 'Latitude'
IgnoredBorderWidths: [0, 10]
RegridOpt: [1, 1]
ForcingTemporalInterpolation: [0, 0]
TemperatureBiasCorrection: [0, 0]
PressureBiasCorrection: [0, 0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,0]
ShortwaveDownscaling: [0,0]
PressureDownscaling: [0,0]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,0]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/AnA", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/AnA"]
SuppPcp: [12]
SuppPcpForcingTypes: ['GRIB2']
SuppPcpDirectories: ['/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/StageIV_CONUS','/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/extended_AnA_CONUS/MRMS_CONUS']
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/AnA'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: ''
custom_input_fcst_freq: []
includeLQFraq: 0
