time_step_seconds: 3600
initial_time: 0
NWM_VERSION: 4.0
NWM_CONFIG: "short_range"
InputForcings: [17,18] 
InputForcingDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/NAM_Nest_PuertoRico", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/WRF_ARW_Puerto_Rico"]
InputForcingTypes: ["GRIB2", "GRIB2"]
InputMandatory: [1,1]
OutputFrequency: 60
SubOutputHour: 0
SubOutFreq: 0
ScratchDir: "./Unit_Test_Output/Short_range"
Output: 0
compressOutput: 0
floatOutput: 0
AnAFlag: 0
LookBack : -9999
RefcstBDateProc: "202302280600"
ForecastFrequency: 720
ForecastShift: 0
ForecastInputHorizons: [2880, 2880]
ForecastInputOffsets: [0, 6]
GeogridIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain_puertorico/geo_em_PRVI.nc"
SpatialMetaIn: "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/domain_puertorico/GEOGRID_LDASOUT_Spatial_Metadata_PRVI.nc"
GRID_TYPE: "gridded"
LONVAR: 'XLONG_M'
LATVAR: 'XLAT_M'
HGTVAR: 'Element_Elevation'
SINALPHA: 'SINALPHA'
COSALPHA: 'COSALPHA'
HGTVAR: 'HGT_M'
IgnoredBorderWidths: [0, 0]
RegridOpt: [1, 1]
ForcingTemporalInterpolation: [0, 0]
TemperatureBiasCorrection: [0, 0]
PressureBiasCorrection: [0, 0]
HumidityBiasCorrection: [0,0]
WindBiasCorrection: [0,0]
SwBiasCorrection: [0,0]
LwBiasCorrection: [0,0]
PrecipBiasCorrection: [0,0]
TemperatureDownscaling: [0,1]
ShortwaveDownscaling: [1,0]
PressureDownscaling: [0,1]
PrecipDownscaling: [0,0]
HumidityDownscaling: [0,1]
DownscalingParamDirs: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/PuertoRico", "/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/PuertoRico"]
SuppPcp: []
SuppPcpForcingTypes: []
SuppPcpDirectories: ["/scratch2/NCEPDEV/ohd/Jason.Ducker/NWM_Forcing_Data/WRF_ARW_Puerto_Rico"]
SuppPcpParamDir: '/scratch2/NCEPDEV/ohd/Jason.Ducker/NWMv3.0_config/parm/forcingParam/PuertoRico'
RegridOptSuppPcp: [1]
SuppPcpTemporalInterpolation: [0]
SuppPcpInputOffsets: [0]
SuppPcpMandatory: [0]
RqiMethod: 0
RqiThreshold: 0.9
cfsEnsNumber: '1'
custom_input_fcst_freq: []
includeLQFrac: 0
